### ISSUE TITLE
dependency was not found:  * history/lib/DOMStateStorage in ./~/react-router-scroll/lib/StateStorage.js

### ISSUE THREAD

**Issue by dalerka** [destepp11/gatsby-store#1]
Hi, thanks for sharing! I'm curious to see this "live" but I keep getting this error when running `gatsby develop`:

>     ERROR  Failed to compile with 1 errors
>     This dependency was not found:
>     * history/lib/DOMStateStorage in ./~/react-router-scroll/lib/StateStorage.js
> 

I tried using upgrading _yarn_ and re-installing deps as suggested in these threads:
https://github.com/gatsbyjs/gatsby/issues/1737
https://github.com/gatsbyjs/gatsby/issues/1809
https://github.com/gatsbyjs/gatsby/issues/1650

Didn't help. What else can I try?

**Comment by beerd7017** [comment]
@dalerka I just updated some of the dependencies in the master branch. Maybe this will resolve the issue?

**Comment by dalerka** [comment]
Thanks! I pulled the updates, ran `yarn` then `cd gatsby-store-/gatsby-site` then `gatsby develop` and it worked.

**Comment by beerd7017** [comment]
Awesome!
